//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zayavki
    {
        public int Id_zakazi { get; set; }
        public int Id_clienta { get; set; }
        public int Id_service { get; set; }
    }
}
